### ISSUE TITLE
Videos microservice fails to deploy

### ISSUE THREAD

**Issue by blanco-lam** [aws-samples/retail-demo-store#212]
Traceback (most recent call last):
File "app.py", line 341, in <module>
start_streams()
File "app.py", line 181, in start_streams
if is_ssm_parameter_set(SSM_VIDEO_CHANNEL_MAP_PARAM) and not USE_DEFAULT_IVS_STREAMS:

File "app.py", line 135, in is_ssm_parameter_set
response = ssm_client.get_parameter(Name=parameter_name)

File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
return self._make_api_call(operation_name, kwargs)

File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore
return xray_recorder.record_subsegment(
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 428, in record_subsegment
subsegment = self.begin_subsegment(name, namespace)
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 292, in begin_subsegment
segment = self.current_segment()
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 270, in current_segment
entity = self.get_trace_entity()
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 390, in get_trace_entity
return self.context.get_trace_entity()
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 99, in get_trace_entity
return self.handle_context_missing()
File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 124, in handle_context_missing
raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open

INFO in app: VIDEO_BUCKET: retail-demo-store-us-west-2
INFO in app: SSM_VIDEO_CHANNEL_MAP_PARAM: retaildemostore-ivs-video-channel-map
INFO in app: USE_DEFAULT_IVS_STREAMS: True
INFO in app: Starting video streams
cannot find the current segment/subsegment, please make sure you have a segment open

**Comment by BastLeblanc** [comment]
hot fix merged. 
We need to check any remaining issues on custom stream, so I'll leave this issue open for now

**Comment by aeggbeg** [comment]
Fairly expensive service. README FAILS to make any note of it anywhere funny :)

**Comment by james-jory** [comment]
> Fairly expensive service. README FAILS to make any note of video services it anywhere funny :)

Hi @aeggbeg. If you deploy with the default IVS streams enabled, there will be no cost for IVS in the account where the project is deployed.
